name: encoderlock
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - torchvision
  - torchaudio
  - tqdm
  - scipy
  - numpy
  - matplotlib
  - opencv
  - lpips
  - cleverhans
  - six
  - astunparse
  - dataclasses
  - setuptools
  - pyyaml
  - cmake
  - cffi
  - requests
  - ninja
  - future
  - mkl-include
  - mkl
  - onnx
  - tsne
  - brokenaxes
  - transformers
