name: encoderlock
channels:
  - pypi
  - conda-forge
dependencies:
  - python=3.9
  - tqdm=4.64.1
  - pip 
  - scipy=1.9.1
  - numpy=1.24.4
  - matplotlib=3.6.0
  - pip:
    - torch==1.12.1  
    - torchvision==0.13.1